# #=
# =========================================================================
# (c) Danmarks Tekniske Universitet 2020
# Script         : Uses output from simulation to create useful plots

# Author         : Corey Kok
# Project        : -
#
# Input:        - df_Objective
#               - df_Input
#               - df_Solution
#
# Output:       - Plots
# =========================================================================
# =#

library(ggplot2)
library(RColorBrewer)
library(scales)
library(reshape2)

Objective.df = read.csv("Output/Objective.csv", header = TRUE)
Input.df = read.csv("Output/Input.csv", header = TRUE)
Solution.df = read.csv("Output/Solution.csv", header = TRUE)

Objective2.df = read.csv("Output/Objective2.csv", header = TRUE)
Input2.df = read.csv("Output/Input2.csv", header = TRUE)
Solution2.df = read.csv("Output/Solution2.csv", header = TRUE)

ObjectiveSum.df = aggregate(Cost ~ SimNum + Model, Objective.df, sum)
ObjectiveSum2.df = aggregate(Cost ~ SimNum + Model, Objective2.df, sum)
d_dn_mean.df = aggregate(d_dn ~ Unit + Stage + Model, Solution.df, mean) 
d_dn_mean2.df = aggregate(d_dn ~ Unit + Stage  + Model, Solution2.df, mean) 

# Boxplot of deferrable load unit's consumption across samples
ggplot(Solution.df[Solution.df$Unit == "j1",], aes(x = factor(Stage), y=d_dn, fill = Model)) + 
    geom_boxplot() + 
    scale_y_continuous("DL Consumption (kWh)", breaks = pretty_breaks()) +
    scale_x_discrete("Stage") +
    scale_fill_brewer('Model', palette = 'Set1') +
    theme(text=element_text(size=15)) +
    facet_grid(Model~.)
ggsave(file="Plots/DL_Consumption.pdf")
ggplot(Solution2.df[Solution2.df$Unit == "j1",], aes(x = factor(Stage), y=d_dn, fill = Model)) + 
    geom_boxplot() + 
    scale_y_continuous("DL Consumption (kWh)", breaks = pretty_breaks()) +
    scale_x_discrete("Stage") +
    scale_fill_brewer('Model', palette = 'Set1') +
    theme(text=element_text(size=15)) +
    facet_grid(Model~.)
ggsave(file="Plots/DL_Consumption2.pdf")

# Mean consumption by Deferrable load unit
ggplot(d_dn_mean.df[d_dn_mean.df$Unit == "j1",], aes(x = Stage, y=d_dn, colour = Model)) + 
    geom_point() + 
    geom_line(linetype = "dotted") +
    scale_y_continuous("Mean DL Consumption (kWh)", breaks = pretty_breaks()) +
    scale_x_continuous("Stage") +
    scale_colour_brewer('Model', palette = 'Set1') +
    theme(text=element_text(size=15)) +
    facet_grid(Model~.)
ggsave(file="Plots/DL_ConsumptionMean.pdf")
ggplot(d_dn_mean2.df[d_dn_mean2.df$Unit == "j1",], aes(x = Stage, y=d_dn, colour = Model)) + 
    geom_point() + 
    geom_line(linetype = "dotted") +
    scale_y_continuous("Mean DL Consumption (kWh)", breaks = pretty_breaks()) +
    scale_x_continuous("Stage") +
    scale_colour_brewer('Model', palette = 'Set1') +
    theme(text=element_text(size=15)) +
    facet_grid(Model~.)
ggsave(file="Plots/DL_ConsumptionMean2.pdf")

# Boxplot of energy storage state across different samples
ggplot(Solution.df[Solution.df$Unit == "j1",], aes(x = factor(Stage), y=e_DL_1, fill = Model)) + 
    geom_boxplot() + 
    scale_y_continuous("Energy Stored (kWh)", breaks = pretty_breaks()) +
    scale_x_discrete("Stage") +
    scale_fill_brewer('Model', palette = 'Set1') +
    theme(text=element_text(size=15)) +
    facet_grid(Model~.)
ggsave(file="Plots/EnergyState.pdf")
ggplot(Solution2.df[Solution2.df$Unit == "j1",], aes(x = factor(Stage), y=e_DL_1, fill = Model)) + 
    geom_boxplot() + 
    scale_y_continuous("DL Consumption (kWh)", breaks = pretty_breaks()) +
    scale_x_discrete("Stage") +
    scale_fill_brewer('Model', palette = 'Set1') +
    theme(text=element_text(size=15)) +
    facet_grid(Model~.)
ggsave(file="Plots/EnergyState2.pdf")

# Overall cost of policy generated by each model
ggplot(ObjectiveSum.df, aes(x = Model, y=Cost, fill = Model)) + 
    geom_boxplot() + 
    scale_y_continuous("Cost (EUR)", breaks = pretty_breaks()) +
    theme(text=element_text(size=15)) +
    scale_fill_brewer('Model', palette = 'Set1') 
ggsave(file="Plots/Cost.pdf")
ggplot(ObjectiveSum2.df, aes(x = Model, y=Cost, fill = Model)) + 
    geom_boxplot() + 
    scale_y_continuous("Cost (EUR)", breaks = pretty_breaks()) +
    theme(text=element_text(size=15)) +
    scale_fill_brewer('Model', palette = 'Set1') 
ggsave(file="Plot/Cost2.pdf")
